import streamlit as st
import requests
import networkx as nx
import matplotlib.pyplot as plt
import os
from neo4j import GraphDatabase
from dotenv import load_dotenv

# Load env variables for Neo4j (to draw the graph)
load_dotenv(os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env'))

st.set_page_config(page_title="AML Fraud Ring Detector", layout="wide")

st.title("🚨 Enterprise AML Fraud Ring Detection")
st.markdown("Enter a Bitcoin Transaction ID to analyze its 2-hop network neighborhood using GraphSAGE and Gemini.")

# Sidebar for input
with st.sidebar:
    st.header("Search Parameters")
    tx_id_input = st.text_input("Transaction ID", value="232438397")
    analyze_btn = st.button("Analyze Transaction", type="primary")

def fetch_graph_data(tx_id):
    """Fetches edges directly from Neo4j for visualization."""
    uri = os.getenv("NEO4J_URI")
    user = os.getenv("NEO4J_USERNAME")
    pwd = os.getenv("NEO4J_PASSWORD")
    
    query = """
    MATCH (target:Transaction {txId: $tx_id})
    OPTIONAL MATCH (target)-[*1..2]-(m:Transaction)
    WITH target, collect(DISTINCT m) AS neighbors
    WITH [target] + neighbors AS nodes
    UNWIND nodes AS n1
    MATCH (n1)-[:PAYS]->(n2:Transaction)
    WHERE n2 IN nodes
    RETURN DISTINCT n1.txId AS source, n2.txId AS target
    """
    driver = GraphDatabase.driver(uri, auth=(user, pwd))
    with driver.session() as session:
        result = session.run(query, tx_id=int(tx_id))
        edges = [(record["source"], record["target"]) for record in result]
    driver.close()
    return edges

if analyze_btn:
    with st.spinner("Querying Graph Database and running AI Inference..."):
        try:
            # 1. Ping our FastAPI Backend
            response = requests.get(f"http://127.0.0.1:8000/predict/{tx_id_input}")
            
            if response.status_code == 200:
                data = response.json()
                
                # --- Top Row: Metrics ---
                col1, col2, col3 = st.columns(3)
                col1.metric("AI Prediction", data['prediction'])
                col2.metric("Confidence", f"{data['confidence']}%")
                col3.metric("Nodes in Subgraph", data['nodes_in_subgraph'])
                
                # --- Middle Row: SAR Report ---
                st.subheader("📝 Suspicious Activity Report (Generated by Gemini)")
                if data['prediction'] == "Illicit":
                    st.error(data['suspicious_activity_report'])
                else:
                    st.success(data['suspicious_activity_report'])
                
                # --- Bottom Row: Graph Visualization ---
                st.subheader("🕸️ Network Topology (2-Hop Neighborhood)")
                edges = fetch_graph_data(tx_id_input)
                
                if edges:
                    G = nx.Graph()
                    G.add_edges_from(edges)
                    
                    fig, ax = plt.subplots(figsize=(10, 6))
                    pos = nx.spring_layout(G, seed=42)
                    
                    # Color the target node blue, others gray
                    node_colors = ['#FF4B4B' if n == int(tx_id_input) else '#A0AEC0' for n in G.nodes()]
                    node_sizes = [300 if n == int(tx_id_input) else 50 for n in G.nodes()]
                    
                    nx.draw_networkx_nodes(G, pos, node_color=node_colors, node_size=node_sizes, alpha=0.8, ax=ax)
                    nx.draw_networkx_edges(G, pos, alpha=0.2, ax=ax)
                    ax.axis('off')
                    
                    st.pyplot(fig)
                else:
                    st.warning("No network connections found for this transaction.")
                    
            else:
                st.error(f"API Error: {response.json().get('detail', 'Unknown error')}")
                
        except Exception as e:
            st.error(f"Failed to connect to backend: {e}")